### ISSUE TITLE
Players gain fly mode after creative.

### ISSUE THREAD

**Issue by FatherWh0** [isokissa3/WorldGuardExtraFlagsPlugin#1]
A player in survival can gain essentials fly mode on by the following procedure.
Visit a creative world.
Teleport directly to a survival world into a fly allow region.
Teleport to a region without the fly flag.
At that point the player can fly and essentials /whois shows fly:true. Running the command /fly <player> will disable their fly mode.
On my server this can be achieved by visiting plot world, then spawn where I have the flag fly allow set, then tping home assuming home is in survival and not in a fly allow region.

WorldGuard Extra Flags 2.11.1
Paper-1004
WorldGuard 6.2

**Comment by isokissa3** [comment]
Fixed?

**Comment by FatherWh0** [comment]
No, it's still an issue. I use 'tricks' to prevent them from tping from a creative world into a survival region with the fly allow flag.

**Comment by isokissa3** [comment]
Is this finally fixed? I can't seem to reproduce the error with old version but with new version the fly flag works more reliable. If I change up words and teleport around it works just fine but on old versions it had some issues.

**Comment by FatherWh0** [comment]
It is fixed. I'm not sure when but a month or so ago I tested and found it no longer occurs. I just tested to verify. I going to hope it's not overstepping my bounds to close this issue.
